### ISSUE TITLE
Request for answer_dict.json for test and dev

### ISSUE THREAD

**Issue by boxin-wbx** [MMMU-Benchmark/MMMU#15]
The `answer_dict_val.jsonl` is very simple and helpful for evaluating the value set of the datasets. 

I am wondering if you have any plan to release the answer dict for the test set and dev set as well to simply the evaluation? Thank you!

**Comment by drogozhang** [comment]
Thanks for your interest. Unfortunately we don't plan to release the answer dict for test set in the near future.

If you want to try your model's performance on the test set, please using our evaluation server hosted on eval.ai.
