### ISSUE TITLE
RuntimeError: The size of tensor a (162) must match the size of tensor b (7) at non-singleton dimension 1

### ISSUE THREAD

**Issue by nrikoh** [MMMU-Benchmark/MMMU#18]
When I run run_llava.py, I get the following error: 
Traceback (most recent call last):
  File "/home/MMMU-main/eval/run_llava.py", line 106, in <module>
    main()
  File "/home/MMMU-main/eval/run_llava.py", line 98, in main
    out_samples = run_model(args, samples, model, call_model_engine, tokenizer, processor)
  File "/home/MMMU-main/eval/run_llava.py", line 23, in run_model
    response = call_model_engine_fn(args, sample, model, tokenizer, processor)
  File "/home/MMMU-main/eval/utils/model_utils.py", line 57, in call_llava_engine_df
    n_diff_input_output = (input_ids != output_ids[:, :input_token_len]).sum().item()
RuntimeError: The size of tensor a (162) must match the size of tensor b (7) at non-singleton dimension 1
What causes this?

**Comment by drogozhang** [comment]
Hi, I never met this situation before, so may be you can try to print the shape of input_ids, output_ids, input_token_len?

**Comment by drogozhang** [comment]
My guess is the llava code update causes the dimension mismatch issue and simply commenting that out would not solve that issue.
I will delve deep into it when I have more time.

**Comment by youngwanLEE** [comment]
@drogozhang @nrikoh The same problem occurs for me.

**Comment by laaambs** [comment]
@nrikoh @youngwanLEE @drogozhang I encountered the same issue. Do you have any solutions?

**Comment by Isaachhh** [comment]
transformers commit@633215ba58fe5114d8c8d32e415a04600e010701 modeling_llama

![image](https://github.com/MMMU-Benchmark/MMMU/assets/93458689/e297eac6-3ff9-41d5-a624-31649dc1f0f1)

You should add "Default to old behavior: keep only FInal ID" back

**Comment by ycszen** [comment]
I have the same issue. The final results are wrong. Any update?

**Comment by ycszen** [comment]
> transformers commit@633215ba58fe5114d8c8d32e415a04600e010701 modeling_llama
> 
> ![image](https://private-user-images.githubusercontent.com/93458689/316279611-e297eac6-3ff9-41d5-a624-31649dc1f0f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDMwOTYsIm5iZiI6MTcxMzgwMjc5NiwicGF0aCI6Ii85MzQ1ODY4OS8zMTYyNzk2MTEtZTI5N2VhYzYtM2ZmOS00MWQ1LWE2MjQtMzE2NDlkYzFmMGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE2MTk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwY2Y5OGM2NjhlYTkwZjkzNjQxNTYzMmIyMTlmZjc3MTA3MmI3ZThlZmY0YjUxZWUzZWU0MWE5YTZmZjVjNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uRfXsy0Md_6pWZyNFt64qJg1hi2apl0_pZwVOLVelvk)
> 
> You should add "Default to old behavior: keep only FInal ID" back

Could you give more details about solving this problem? Thanks.

**Comment by Isaachhh** [comment]
> Could you give more details about solving this problem? Thanks.

Find the source code of transformers in your enviroment (may be `anaconda3/envs/xxxx/lib/python3.10/site-packages/transformers/models/llama`), and then edit the `modeling_llama.py` by adding the branch of "Default to old behavior: keep only FInal ID" back.

Like this:
![image](https://github.com/MMMU-Benchmark/MMMU/assets/93458689/4e96a966-fe39-4e88-8a5d-25258d4e5745)

**Comment by kyleliang919** [comment]
@Isaachhh Sorry I don't fully understand the implication of this change. Is it just removing the input context all together?

**Comment by drogozhang** [comment]
Hi,
Sry for being busy previously, here is the simpler solution I found:

when installing llava following the instructions, go back to `tags/v1.1.3` version before installation.

i.e.,
nothing changed in step 1:
```
git clone https://github.com/haotian-liu/LLaVA.git
cd LLaVA
```
In Step 2:
```
conda create -n llava python=3.10 -y
conda activate llava
pip install --upgrade pip  # enable PEP 660 support
git fetch --tags  # newly added.
git checkout tags/v1.1.3  # newly added.
pip install -e .
```

This will install older llava (1.5 only) and corresponding correct transformers version.

Hope it helps!

**Comment by drogozhang** [comment]
Have just updated the readme as well. let me know if you have any other questions.
