### ISSUE TITLE
gpt4v refuse to answer/ insist on "I'm sorry, but I'm unable to view images" these kind of things

### ISSUE THREAD

**Issue by SweetGUOguo** [MMMU-Benchmark/MMMU#19]
Thanks a lot for your effort!!! 
Can I ask if you are experiencing gpt4v refusing to answer/insisting that there is no image provided when you validate gpt4v with mmmu? 
I came across the issue above when I tried to send gpt4v the mmmu dataset...

Thanks a lot again!!!!!!!!!!

**Comment by drogozhang** [comment]
gpt4v is well aligned.
So better insist them to provide answers even gpt4v claims it cannot view images.

**Comment by SweetGUOguo** [comment]
Thank you!!!
