### ISSUE TITLE
Fail to connect to the homepage: https://mmmu-benchmark.github.io/

### ISSUE THREAD

**Issue by shannany0606** [MMMU-Benchmark/MMMU#21]
I'm sorry to hear that the homepage is not available right now. I hope you can fix it soon.

**Comment by drogozhang** [comment]
Hi, the website works fine on my side, could you please elaborate the unavailable issue a bit more?

**Comment by shannany0606** [comment]
No thing wrong. I can view the homepage at home. Thanks.
