### ISSUE TITLE
There's an error in one of the Correct Examples for genetics

### ISSUE THREAD

**Issue by eabase** [MMMU-Benchmark/MMMU#22]
Looking through the Correct Examples I came across the genetics example, and it is wrong. 

![2024-0427_173712_MMMU_—_Mozilla_Firefox](https://github.com/MMMU-Benchmark/MMMU/assets/52289379/36409d38-0557-449c-9280-dc4e932f261c)

- The numbers doesn't correspond to what's in the image. 
- The logic/reasoning shown is regardless incorrect even if numbers had been ok. 

It would be interesting to know how you guys are wetting what is considered to be correct?

**Comment by NipElement** [comment]
Thank you for bringing this to our attention!
The example you mentioned is not a good example, and we will remove it.  However, it will still be counted as a correct answer based on our extraction logic.

**Comment by eabase** [comment]
@NipElement 
> _However, it will still be counted as a correct answer based on our extraction logic._

Sorry, I don't understand.  
Why would you "count" something that is wrong, as being correct?

**Comment by NipElement** [comment]
Because the final performance evaluation relies on extracting answers, and even answers that might only be guessed correctly are taken into account. You can find more about the extraction logic from our evaluation code. It is challenging to verify all responses provided by each model.

**Comment by drogozhang** [comment]
Hi All, it is a parsing error in our answer extraction code part. It will introduce about 1% errors for some models.

To avoid such issues, people who are interested in evaluating their own models can extract the response themselves and submit the extracted answer directly, instead of the raw response.
