### ISSUE TITLE
GPT4o

### ISSUE THREAD

**Issue by dirtycomputer** [MMMU-Benchmark/MMMU#24]
GPT-4o (“o” for “omni”) is openai's most advanced model. It is multimodal (accepting text or image inputs and outputting text), and it has the same high intelligence as GPT-4 Turbo but is much more efficient—it generates text 2x faster and is 50% cheaper. Additionally, GPT-4o has the best vision and performance across non-English languages of any of openai's models. GPT-4o is available in the OpenAI API to paying customers. [https://platform.openai.com/docs/models/gpt-4o](https://platform.openai.com/docs/models/gpt-4o)

**Comment by xiangyue9607** [comment]
Thanks! We are aware of this model and will add it to our leaderboard.

**Comment by dirtycomputer** [comment]
Once you have completed the evaluation, I would greatly appreciate it if you could notify me on this issue interface.

**Comment by insafim** [comment]
I am only getting Overall: 921 / 1730 (53.2%) for GPT-4o for the Standard 4-options case. Did you get the accuracy mentioned in the paper? (64.7)
