### ISSUE TITLE
How to convert images and prompt to the HF parquet?

### ISSUE THREAD

**Issue by Gumpest** [MMMU-Benchmark/MMMU#25]
Could you please provide the conversion script?

**Comment by drogozhang** [comment]
This is the file I used to convert local files to huggingface https://github.com/sayakpaul/instruct-pix2pix-dataset
Not sure how heavily @NipElement edited for MMMU case. Could you answer this question? @NipElement

**Comment by NipElement** [comment]
You can use the `.push_to_hub()` function to upload a dataset to HF. It will automatically convert it into a `parquet` file (remember to update your `datasets` version).
