### ISSUE TITLE
Enquiry about the usage about your dataset

### ISSUE THREAD

**Issue by tunantu** [MMMU-Benchmark/MMMU#33]
Hi, authors, thanks for your work. I am curious about the usage about your dataset, i.e., how to load the dataset, how to get the corresponding text and image. Meanwhile, I had looked throught the page about your hugging face, unfortunately, I did not get it. So could you release a simple example about how to use this dataset?

Many thanks.

**Comment by xiangyue9607** [comment]
Thank you! The script is now available at https://github.com/MMMU-Benchmark/MMMU/tree/main/mmmu-pro
