### ISSUE TITLE
BIG BUG!

### ISSUE THREAD

**Issue by warm345** [MMMU-Benchmark/MMMU#37]
I would like to ask, since your inference script does not support multi-image testing, why do you need to include multi-image content in the test set?
```
    if len(o_imgs_paths) > 1:  # multiple images in options, used for random selection
        return {'id': data['id'], 'question': question, 'options': data['options'], 'answer': data['answer'],
             'image': None, 'question_type': data['question_type']}
```

When there are more than one image, you randomly select one, which greatly affects the benchmark standard! !

Secondly, in your logic, `data['options']` is a string, and when you iterate over it, you are iterating over the string, not the list! !
```    for option in data['options']:
        current_o_imgs_paths = parse_img_path(option)
        for img_path in current_o_imgs_paths:
            o_imgs_paths.append(img_path)
```

**Comment by drogozhang** [comment]
Close the issue for inactivity for now. Feel free to re-open it if you have any other questions.
