### ISSUE TITLE
Temperature setting

### ISSUE THREAD

**Issue by starriver030515** [MMMU-Benchmark/MMMU#38]
Hi! I encounered some problems when reproducing the results. I noticed that in the llava1.5 YAML file, the temperature is set to 0, but in the model_utils.py file, the temperature is still set to 1. Which temperature setting corresponds to the leaderboard evaluations?

**Comment by drogozhang** [comment]
We use default temp setting if the official model repo provides that (such as temp 1 for llava1.5). If not, we use zero.

I found temp 1 will not change the eval results too much, esp on the test set.

**Comment by starriver030515** [comment]
Thanks, I will try again.
