### ISSUE TITLE
Error reports when loading the dataset

### ISSUE THREAD

**Issue by XiongweiWu** [MMMU-Benchmark/MMMU#4]
Hi, I am try to load your dataset with the provided command: 
`from datasets import load_dataset`
`dataset = load_dataset("MMMU/MMMU")`

However, one error reports as:

> ExpectedMoreSplits: {'dev'}

Can u check it?

**Comment by NipElement** [comment]
Thank you for using our dataset! 
Because the  dataset includes multiple subsets, and you need to specify which subset you want to load.
To resolve this, you should specify the subset while loading the dataset like follow:
```
from datasets import load_dataset
dataset = load_dataset("MMMU/MMMU", 'Computer_Science')
```
Let us know if you have any further issues.

**Comment by yushihu-uchicago** [comment]
I was meeting the same problem and I solved it by updating my datasets package. @XiongweiWu you may try it.

**Comment by Yushi-Hu** [comment]
I was meeting the same problem and I solved it by updating my datasets package. @XiongweiWu you may try it.

**Comment by XiongweiWu** [comment]
@Yushi-Hu Thx for your help! After upgrading the datasets to 2.15.0, the problem is solved.
