### ISSUE TITLE
MMMU-Pro 4 Choices

### ISSUE THREAD

**Issue by insafim** [MMMU-Benchmark/MMMU#40]
You have shown results on both 4 choices and 10 choices cases. But, in HF only 10 choices are available. How can I get the 4 choices for all the questions?

**Comment by xiangyue9607** [comment]
Thanks for the comment! 

@NipElement Maybe we should also release the original 4 options of MMMU-Pro?

**Comment by NipElement** [comment]
Thanks for the advice, we have released 4 choice cases on HF, please check the latest version!

**Comment by insafim** [comment]
Thank you for your prompt response.

**Comment by insafim** [comment]
Following Questions have more than 4 options. Standard (4 options) in HF

['test_Agriculture_195', 'validation_Physics_7', 'test_Biology_321', 'test_Agriculture_169', 'test_Diagnostics_and_Laboratory_Medicine_28', 'test_Biology_146', 'validation_Basic_Medical_Science_1', 'validation_Diagnostics_and_Laboratory_Medicine_16', 'validation_Biology_25', 'test_Biology_328', 'test_Agriculture_4', 'validation_Biology_8', 'test_Diagnostics_and_Laboratory_Medicine_126', 'validation_Manage_30', 'test_Computer_Science_158', 'test_Agriculture_92', 'validation_Psychology_17', 'test_Biology_19', 'test_Agriculture_269', 'test_Psychology_105', 'validation_Psychology_8', 'test_Diagnostics_and_Laboratory_Medicine_161', 'test_Chemistry_447', 'test_Agriculture_8', 'validation_Biology_20', 'validation_Psychology_7', 'validation_Agriculture_27', 'test_Finance_10', 'validation_Agriculture_10', 'test_Psychology_258', 'test_Clinical_Medicine_314', 'test_Economics_137', 'test_Economics_7', 'validation_Agriculture_8', 'test_Agriculture_248', 'test_Agriculture_187', 'test_Biology_47', 'validation_Agriculture_29', 'validation_Biology_22', 'test_Biology_318', 'validation_Clinical_Medicine_1', 'validation_Diagnostics_and_Laboratory_Medicine_1', 'test_Clinical_Medicine_153', 'validation_Agriculture_4', 'test_Psychology_21', 'validation_Public_Health_16', 'test_Chemistry_197', 'test_Agriculture_39', 'test_Basic_Medical_Science_158', 'validation_Economics_4', 'validation_Clinical_Medicine_20', 'test_Physics_201', 'validation_Basic_Medical_Science_18', 'validation_Clinical_Medicine_8', 'test_Diagnostics_and_Laboratory_Medicine_92', 'validation_Clinical_Medicine_25', 'test_Clinical_Medicine_114', 'test_Psychology_270', 'validation_Physics_9', 'test_Materials_423', 'test_Biology_249', 'test_Diagnostics_and_Laboratory_Medicine_72', 'test_Math_476', 'test_Agriculture_192', 'validation_Manage_8', 'test_Math_115', 'test_Psychology_285', 'test_Diagnostics_and_Laboratory_Medicine_64', 'validation_Biology_14', 'validation_Chemistry_2', 'test_Computer_Science_367', 'validation_Materials_24', 'test_Diagnostics_and_Laboratory_Medicine_143', 'test_Biology_341', 'test_Agriculture_271', 'validation_Diagnostics_and_Laboratory_Medicine_3', 'test_Music_39', 'validation_Clinical_Medicine_18', 'test_Agriculture_15', 'test_Manage_94', 'test_Agriculture_183', 'test_Agriculture_217', 'test_Biology_8', 'test_Manage_8', 'test_Materials_450', 'test_Chemistry_481', 'validation_Psychology_30', 'validation_Manage_24', 'validation_Psychology_6', 'test_Manage_177', 'test_Chemistry_43', 'test_Psychology_83', 'validation_Physics_30', 'validation_Psychology_15', 'test_Agriculture_139', 'test_Psychology_33', 'test_Geography_114', 'test_Geography_150', 'test_Agriculture_69', 'validation_Biology_21', 'validation_Clinical_Medicine_16', 'validation_Computer_Science_24', 'test_Agriculture_42', 'test_Psychology_228', 'test_Chemistry_366', 'test_Agriculture_190', 'validation_Biology_9', 'validation_Agriculture_22', 'test_Agriculture_55', 'test_Agriculture_157', 'validation_Agriculture_17', 'test_Agriculture_282', 'validation_Diagnostics_and_Laboratory_Medicine_27', 'validation_Math_22', 'test_Agriculture_46', 'test_Agriculture_19', 'test_Chemistry_400', 'validation_Computer_Science_5', 'test_Biology_310', 'validation_Agriculture_18', 'test_Psychology_44', 'test_Economics_157', 'validation_Clinical_Medicine_22', 'test_Geography_521', 'test_Agriculture_270', 'test_Clinical_Medicine_247', 'test_Clinical_Medicine_126', 'test_Biology_196', 'test_Manage_234', 'test_Chemistry_582', 'validation_Diagnostics_and_Laboratory_Medicine_10', 'validation_Psychology_3', 'test_Agriculture_262', 'test_Clinical_Medicine_316', 'validation_Agriculture_13', 'test_Biology_46', 'test_Diagnostics_and_Laboratory_Medicine_2', 'test_Diagnostics_and_Laboratory_Medicine_24', 'test_Math_266', 'test_Biology_175', 'test_Biology_259', 'test_Chemistry_362', 'validation_Computer_Science_1', 'test_Psychology_149', 'test_Chemistry_102', 'validation_Chemistry_22', 'test_Agriculture_145', 'test_Biology_307', 'test_Clinical_Medicine_68', 'test_Agriculture_37', 'test_Clinical_Medicine_298', 'validation_Chemistry_11', 'validation_Agriculture_20', 'validation_Biology_30', 'test_Chemistry_417', 'validation_Diagnostics_and_Laboratory_Medicine_20', 'validation_Math_30', 'test_Basic_Medical_Science_46', 'validation_Sociology_30', 'test_Computer_Science_120', 'test_Chemistry_193', 'test_Math_282', 'test_Chemistry_555', 'test_Agriculture_165', 'test_Agriculture_146', 'test_Agriculture_207', 'test_Materials_150', 'validation_Diagnostics_and_Laboratory_Medicine_15', 'validation_Diagnostics_and_Laboratory_Medicine_24', 'test_Chemistry_11', 'validation_Biology_29', 'test_Clinical_Medicine_164', 'test_Psychology_220', 'validation_Diagnostics_and_Laboratory_Medicine_19', 'validation_Chemistry_16', 'test_Computer_Science_89', 'test_Clinical_Medicine_118', 'test_Geography_213', 'test_Design_56', 'test_Chemistry_40', 'test_Psychology_128', 'test_Diagnostics_and_Laboratory_Medicine_76', 'test_Clinical_Medicine_69', 'test_Basic_Medical_Science_233', 'test_Diagnostics_and_Laboratory_Medicine_52', 'test_Agriculture_102', 'test_Agriculture_117', 'test_Physics_386', 'test_Computer_Science_309', 'test_Biology_142', 'test_Agriculture_234', 'test_Math_16', 'test_Clinical_Medicine_128', 'validation_History_10', 'test_Agriculture_123', 'validation_Biology_27', 'validation_Basic_Medical_Science_23', 'test_Economics_155', 'validation_Computer_Science_15', 'validation_Psychology_1', 'test_Agriculture_93', 'test_Math_165', 'test_Basic_Medical_Science_247', 'validation_Agriculture_5', 'test_Diagnostics_and_Laboratory_Medicine_36', 'validation_Biology_13', 'validation_Psychology_13', 'validation_Agriculture_23', 'test_Agriculture_278', 'test_Electronics_178', 'test_Materials_446', 'test_Agriculture_178', 'test_Diagnostics_and_Laboratory_Medicine_135', 'test_Clinical_Medicine_172', 'test_Math_436', 'validation_Agriculture_3', 'test_Economics_169', 'test_Biology_160', 'test_Psychology_293', 'validation_Agriculture_9', 'test_Biology_183', 'test_Agriculture_193', 'validation_Chemistry_6', 'test_Geography_14', 'test_Geography_38', 'test_Geography_45', 'test_Geography_42']

**Comment by insafim** [comment]
Can you please correct this and re-upload

**Comment by xiangyue9607** [comment]
Hi, 

There exist cases where options are less than 4 or more than 4 in the standard (4 options) scenarios. Similarly, in the "10 options" setting, there are also cases where options are less than 10.

**Comment by insafim** [comment]
I see. Thank you for the clarification. So the results on the paper are based on the dataset uploaded in HF which has such cases (less than 4 or more than 4 in the standard (4 options) scenarios) right?

**Comment by xiangyue9607** [comment]
Yes!

**Comment by Violettttee** [comment]
Hi~

**Comment by xiangyue9607** [comment]
@Violettttee Hi! The leaderboard uses 10 options.
