### ISSUE TITLE
Answer not present in the model prediction

### ISSUE THREAD

**Issue by insafim** [MMMU-Benchmark/MMMU#41]
When using the cot prompt, didn't you encounter instances where the A/B/C/D answer is absent in the model output.

So in that case using regex to extract answers will not work leading to lower accuracy.

**Comment by insafim** [comment]
@xiangyue9607 @NipElement Can you please clarify this.

**Comment by Zheng0428** [comment]
If the model output lacks the A/B/C/D answers, it indicates poor instruction-following ability or an inability to make a clear judgment, which reasonably contributes to lower accuracy.
