### ISSUE TITLE
How are the image types defined and labeled?

### ISSUE THREAD

**Issue by CCYChongyanChen** [MMMU-Benchmark/MMMU#6]
Great work! Could I ask how are the image types defined and labeled? Thanks!

**Comment by xiangyue9607** [comment]
Hi, 

Thanks for the question. We first compiled a long list covering different types of images in different subjects with the help of GPT-4 and other information online. We then showed the list to the annotators and let them select one or more image types for the image(s) in each example. If none of them matched the pre-defined list, they would mark it as "Other".

Hope it helps!

Best,
Xiang

**Comment by xiangyue9607** [comment]
close the issue. let us know if you have further questions
